name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - run: |
          TMP="$(mktemp -d)"
          git clone https://github.com/rust-lang/rust-clippy "$TMP"
          cd "$TMP"
          # git checkout 15ed281699802aae2364b77a4e9900a9acad3d0d
          # git checkout dd8e44c5a22ab646821252604420c5bb82c36aa9 passed
          # git checkout 588c1abb7 passed
          # git checkout d65c4595e failed
          git checkout b5bfd1176
          cargo uitest
